services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: |
      # Install dependencies directly (no build.sh needed)
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
